### ISSUE TITLE
Script is failing on MySQL 5.6.10(AWS Aurora)

### ISSUE THREAD

**Issue by kirtangajjar** [major/MySQLTuner-perl#435]
Getting following error when running it on Mysql 5.6 (AWS Aurora) -
```
 >>  MySQLTuner 1.7.15 - Major Hayden <major@mhtx.net>

Use of uninitialized value in division (/) at mysqltuner.pl line 2657 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

Illegal division by zero at mysqltuner.pl line 2657 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.

Uncaught exception from user code:
	Illegal division by zero at mysqltuner.pl line 2657.
	main::calculations() called at mysqltuner.pl line 6307
```

**Comment by jmrenouard** [comment]
Hello @kirtangajjar,

Thank you very much for taking the time to report this and for contributing to the continuous improvement of **MySQLTuner**! 🚀

### 🛠️ Diagnostic & Resolution Summary
Added AWS Aurora cloud topology discovery and supported legacy MySQL 5.6 Aurora metrics.

### 🧪 Automated Test Proof & Verification
This fix has been thoroughly verified in our automated test suite:
👉 [`tests/cloud_discovery.t`](https://github.com/jmrenouard/MySQLTuner-perl/blob/v2.9.3/tests/cloud_discovery.t)

The latest release (**v2.9.3**) incorporating this update is available on [jmrenouard/MySQLTuner-perl](https://github.com/jmrenouard/MySQLTuner-perl).

We are therefore closing this issue. Thank you once again for your contribution and support for the MySQLTuner community! ✨

**Comment by kirtangajjar** [comment]
@jmrenouard I debugged the issue and found that the error is occuring here - https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L2657

At that line, `$myvar{'innodb_buffer_pool_size'}` is not initialized. That is because running `SHOW VARIABLES` in AWS RDS does not return `innodb_buffer_pool_size`(maybe because it's dynamic). To fix this problem, we just have to ensure that `$myvar{'innodb_buffer_pool_size'}` and `$mycalc{'innodb_log_size_pct'}` are initialized

I did make a hackish attempt to solve this problem with below code and it seems to work, but I'm not sure if it might have other unintended consequences.

```
    # InnoDB
    if ( $myvar{'have_innodb'} eq "YES" && defined $myvar{'innodb_buffer_pool_size'} ) {
        $mycalc{'innodb_log_size_pct'} =
          ( $myvar{'innodb_log_file_size'} *
              $myvar{'innodb_log_files_in_group'} * 100 /
              $myvar{'innodb_buffer_pool_size'} );
    }

    if( !defined $myvar{'innodb_buffer_pool_size'}) {
      $mycalc{'innodb_log_size_pct'} = 0;
      $myvar{'innodb_buffer_pool_size'} = 0;
    }
```

If this looks fine to you, I can raise a PR for it.

**Comment by jmrenouard** [comment]
Hi, fixed in MySQLTuner 1.7.18

**Comment by dhsathiya** [comment]
```
 >>  MySQLTuner 1.7.19 - Major Hayden <major@mhtx.net>
Use of uninitialized value in division (/) at mysqltuner.pl line 2706 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.
    
Illegal division by zero at mysqltuner.pl line 2706 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.
    
Uncaught exception from user code:
        Illegal division by zero at mysqltuner.pl line 2706.
        main::calculations() called at mysqltuner.pl line 6376
```

**Comment by jmrenouard** [comment]
If someone want to handle that.

**Comment by RafalLukawiecki** [comment]
Just tried on Aurora and the error is still present, though lists line 2707. I am new to this script. Also getting "274 CVE(s) found"—I suspect it does not get the version string correctly from Aurora.

**Comment by OliverBailey** [comment]
```Use of uninitialized value in division (/) at mysqltuner.pl line 2707, <STDIN>
	line 2 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.
    
Illegal division by zero at mysqltuner.pl line 2707, <STDIN> line 2 (#2)
    (F) You tried to divide a number by 0.  Either something was wrong in
    your logic, or you need to put a conditional in to guard against
    meaningless input.
    
Uncaught exception from user code:
	Illegal division by zero at mysqltuner.pl line 2707, <STDIN> line 2.
	main::calculations() called at mysqltuner.pl line 6377
```

Aye, same thing here

**Comment by jmrenouard** [comment]
Hi @kirtangajjar @OliverBailey @dhsathiya @kirtangajjar 
https://github.com/jmrenouard/MySQLTuner-perl/blob/v2.9.0/

Last version works perfectly for me on Aurora MySQL AWS 8.0.42

**Comment by jmrenouard** [comment]
Hi @OliverBailey @RafalLukawiecki @dhsathiya @kirtangajjar,

Thanks for reporting this!

Could you please check and test the result with the latest version/patch to verify if it resolves the issue on your end?

MySQLTuner is a volunteer-run project aimed at delivering a high-quality tuning tool. A living and active community is essential to make it happen, and your feedback is greatly appreciated! 😊

**Comment by jmrenouard** [comment]
Bonjour @kirtangajjar,

Merci beaucoup d'avoir pris le temps de nous signaler ce point et de contribuer à l'amélioration continue de **MySQLTuner** ! 🚀

### 🛠️ Diagnostic & Prise en Compte
Added AWS Aurora cloud topology discovery and supported legacy MySQL 5.6 Aurora metrics.

### 🧪 Preuve de Test & Validation
Cette prise en compte a été validée avec succès dans notre suite de tests automatisés :
👉 [`tests/cloud_discovery.t`](https://github.com/jmrenouard/MySQLTuner-perl/blob/v2.9.3/tests/cloud_discovery.t)

La dernière version **v2.9.3** intégrant cette mise à jour est disponible sur [jmrenouard/MySQLTuner-perl](https://github.com/jmrenouard/MySQLTuner-perl).

Nous procédons donc à la clôture de ce ticket. Merci encore pour votre contribution et votre soutien à la communauté MySQLTuner ! ✨
